"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$git_state\
$all\
$line_break\
$character
"""

# Use the color palette
palette = "dracula"

# Define Dracula color palette
[palettes.dracula]
white = "#ffffff"
background = "#282a36"
current_line = "#44475a"
gray = "#313243"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
black = "#000000"
beige = "#F9F0E1"
beige_dark = "#6E644E"

[character]
success_symbol = "[I îªŸ ](bold fg:green)"
error_symbol = '[âœ˜  îªŸ ](bold fg:red)'
vimcmd_symbol = "[N îªŸ ](bold fg:purple)"
vimcmd_replace_one_symbol = "[ó°¿  îªŸ ](bold fg:purple)"
vimcmd_replace_symbol = "[ï¹  îªŸ ](bold fg:purple)"
vimcmd_visual_symbol = "[ï®  îªŸ ](bold fg:cyan)"

[username]
format = "[$user]($style) on "
style_user = "bold cyan"

[cmd_duration]
style = "bold yellow"
disabled = true

[aws]
symbol = "îŒ½  "
style = "bold orange"

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[cmake]
symbol = "î” "

[conda]
symbol = "ï„Œ "

[crystal]
symbol = "î˜¯ "

#============================================= dart =============================================
[dart]
symbol = "[î‚¶](gray)î˜ "
style = "fg:white bold bg:gray"
format = ' [$symbol$version]($style)[î‚´](gray)'

#============================================= Directory =============================================
[directory]
read_only = " ó°Œ¾"
style = "fg:white bold bg:black"
read_only_style = "bold red"
format = '[$path]($style)[$read_only]($read_only_style) '
home_symbol = "/Users/abba"
truncation_length = 0

[directory.substitutions]
"documents" = "Documents ó°ˆ™ "
"Downloads" = "Downloads ï€™ "
"Music" = "Music î°› "
"Pictures" = "Pictures ï€¾ "
"others" = "ï‡ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î˜­ "

[elm]
symbol = "î˜¬ "

[fennel]
symbol = "îš¯ "

[fossil_branch]
symbol = "ï˜ "

#============================================= Git =============================================
[git_commit]
tag_symbol = ' ï’ '

[git_branch]
symbol = "ïˆ  ï˜ "
style = "fg:white bold bg:gray"
format = "[î‚¶](gray)[$symbol$branch]($style)"

[git_status]
format = '[ ](bg:gray)[(fg:white bg:gray)[$all_status]($style)](fg:white bg:gray)[î‚´](gray)'
style = "bg:gray"
conflicted = "[= ](fg:red bold bg:gray)"
stashed = '[\$$count ](fg:orange bg:gray)'
deleted = '[-$count ](fg:red bold bg:gray)'
renamed = '[Â»$count ](fg:purple bold bg:gray)'
modified = '[!$count ](fg:cyan bold bg:gray)'
staged = '[+$count ](fg:green bold bg:gray)'
untracked = '[?$count ](fg:yellow bold bg:gray)'
ahead = '[â‡¡ $count ](fg:green bold bg:gray)'
behind = '[â‡£ $count ](fg:red bold bg:gray)'
diverged = '[â‡• \(â‡¡ $ahead_countï–â‡£ $behind_count\) ](fg:orange bold bg:gray)'

#============================================= Golang =============================================
[golang]
symbol = "[î‚¶](gray)î˜§ "
style = "fg:white bold bg:gray"
format = ' [$symbol$version]($style)[î‚´](gray)'

[guix_shell]
symbol = "ïŒ¥ "

[haskell]
symbol = "î· "

[haxe]
symbol = "î™¦ "

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "
style = "bold purple"

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[kotlin]
symbol = "î˜´ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ó°› "

[meson]
symbol = "ó°”· "

[nim]
symbol = "ó°†¥ "

[nix_shell]
symbol = "ïŒ“ "

#============================================= bun =============================================
[bun]
symbol = "[î‚¶](gray)î¯ "
style = "fg:white bold bg:gray"
format = ' [$symbol$version]($style)[î‚´](gray)'
#============================================= node =============================================
[nodejs]
symbol = "[î‚¶](gray)îœ˜ "
style = "fg:white bold bg:gray"
format = ' [$symbol$version]($style)[î‚´](gray)'

[ocaml]
symbol = "î™º "

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

#============================================= package =============================================
[package]
symbol = "[î‚¶](gray)ó°— "
style = "fg:white bold bg:gray"
format = ' [$symbol$version]($style)[î‚´](gray)'

[php]
symbol = "î˜ˆ "

[pijul_channel]
symbol = "ï˜ "

[python]
symbol = "[î‚¶](gray)îˆµ "
style = "fg:white bold bg:gray"
format = ' [$symbol$version]($style)[î‚´](gray)'

[rlang]
symbol = "ó°Ÿ” "

#============================================= ruby =============================================
[ruby]
symbol = "[î‚¶](gray)î‘ "
style = "fg:white bold bg:gray"
format = ' [$symbol$version]($style)[î‚´](gray)'

#============================================= rust =============================================
[rust]
symbol = "[î‚¶](gray)ğŸ¦€ "
style = "fg:white bold bg:gray"
format = ' [$symbol$version]($style)[î‚´](gray)'

[swift]
symbol = "î• "

[zig]
symbol = "îš© "

[gradle]
symbol = "î™  "
