#============================================= Configs =============================================
[[session]]
name = "sesh-config"
path = "~/Documents/dotfiles/.config/sesh/"
startup_command = "nvim sesh.toml"

#============================================= Projects =============================================
#---- React Native ----
[[session]]
name = "join-queue-business"
path = "~/Documents/join-queue-business/"
startup_command = "~/.config/sesh/scripts/three-splits.sh"

[[session]]
name = "join-queue-customer"
path = "~/Documents/join-queue-customer/"
startup_command = "~/.config/sesh/scripts/three-splits.sh"

#---- rust ----
[[session]]
name = "bdk_wallet"
path = "~/Documents/bdk_wallet/"
startup_command = "~/.config/sesh/scripts/two-splits.sh"

#============================================= tools =============================================
[[session]]
name = "http-client"
path = "~/Documents/api-collections/"
startup_command = "~/.config/sesh/scripts/open-in-nvim.sh"

[[session]]
name = "notes"
path = "~/Documents/shytypes-obs-vault/"
startup_command = "kvim -c 'lua require(\"persistence\").load()'"
