#============================================= Configs =============================================
[[session]]
name = "dotfiles"
path = "~/Documents/dotfiles/"
startup_command = "~/.config/sesh/scripts/two-splits.sh"

#============================================= Projects =============================================
#---- React Native ----
[[session]]
name = "join-queue-business"
path = "~/Documents/join-queue-business/"
startup_command = "~/.config/sesh/scripts/three-splits.sh"

[[session]]
name = "join-queue-customer"
path = "~/Documents/join-queue-customer/"
startup_command = "~/.config/sesh/scripts/three-splits.sh"

#---- rust ----
[[session]]
name = "bdk_wallet"
path = "~/Documents/bdk_wallet/"
startup_command = "~/.config/sesh/scripts/two-splits.sh -w -c"

[[session]]
name = "btc_test_area"
path = "~/Documents/btc_test_area/"
startup_command = "~/.config/sesh/scripts/open-in-nvim.sh '  Editor' && nvim -c 'lua require(\"persistence\").load()'"

[[session]]
name = "rust-esplora-client"
path = "~/Documents/rust-esplora-client/"
startup_command = "~/.config/sesh/scripts/two-splits.sh -w -c"

#============================================= tools =============================================
[[session]]
name = "http-client"
path = "~/Documents/api-collections/"
startup_command = "~/.config/sesh/scripts/open-in-nvim.sh '  HTTP Client'"

[[session]]
name = "btop"
path = "~"
startup_command = "~/.config/sesh/scripts/app-window-fmt.sh '  btop' && btop"

[[session]]
name = "notes"
path = "~/Documents/shytypes-obs-vault/"
startup_command = "~/.config/sesh/scripts/app-window-fmt.sh '󰠮  notes' && nvim -c 'lua require(\"persistence\").load()'"

[[session]]
name = "opencode"
path = "~"
startup_command = "~/.config/sesh/scripts/app-window-fmt.sh '  opencode' && opencode"

[[session]]
name = "spf"
path = "~"
startup_command = "~/.config/sesh/scripts/app-window-fmt.sh '  superfile' && spf"
